//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerrazIrrigacoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensOrcamento
    {
        public int id { get; set; }
        public Nullable<decimal> ValorProduto { get; set; }
        public Nullable<int> Orcamento { get; set; }
        public Nullable<int> Produto { get; set; }
        public Nullable<int> quantidade { get; set; }
    
        public virtual Orcamento Orcamento1 { get; set; }
        public virtual Produto Produto1 { get; set; }
    }
}
