//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerrazIrrigacoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lancamento
    {
        public int Id { get; set; }
        public string Movimento { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Venda { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> CaixaId { get; set; }
    
        public virtual Venda Venda1 { get; set; }
    }
}
