//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerrazIrrigacoes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sakitadbEntities : DbContext
    {
        public sakitadbEntities()
            : base("name=sakitadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caixa> Caixa { get; set; }
        public virtual DbSet<CategoriasTipo> CategoriasTipo { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<FormaDePagamento> FormaDePagamento { get; set; }
        public virtual DbSet<ItensOrcamento> ItensOrcamento { get; set; }
        public virtual DbSet<ItensVenda> ItensVenda { get; set; }
        public virtual DbSet<Lancamento> Lancamento { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Orcamento> Orcamento { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<UnidadeMedidaTipos> UnidadeMedidaTipos { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venda> Venda { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> CalculaCaixa(Nullable<int> caixaId)
        {
            var caixaIdParameter = caixaId.HasValue ?
                new ObjectParameter("CaixaId", caixaId) :
                new ObjectParameter("CaixaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CalculaCaixa", caixaIdParameter);
        }
    }
}
