//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerrazIrrigacoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orcamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orcamento()
        {
            this.ItensOrcamento = new HashSet<ItensOrcamento>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> dataorcamento { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Venda { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensOrcamento> ItensOrcamento { get; set; }
        public virtual Venda Venda1 { get; set; }
    }
}
