//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerrazIrrigacoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.ItensOrcamento = new HashSet<ItensOrcamento>();
            this.ItensVenda = new HashSet<ItensVenda>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Estoque { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Marca { get; set; }
        public Nullable<int> CategoriasTipo { get; set; }
        public Nullable<int> UnidadeMedidaTipos { get; set; }
    
        public virtual CategoriasTipo CategoriasTipo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensOrcamento> ItensOrcamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensVenda> ItensVenda { get; set; }
        public virtual Marca Marca1 { get; set; }
        public virtual UnidadeMedidaTipos UnidadeMedidaTipos1 { get; set; }
    }
}
