//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerrazIrrigacoes.Models
{
    using System;
    using System.Collections.Generic;    
    using System.ComponentModel.DataAnnotations;

    public partial class Venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venda()
        {
            this.ItensVenda = new HashSet<ItensVenda>();
            this.Lancamento = new HashSet<Lancamento>();
            this.Orcamento = new HashSet<Orcamento>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:C}")]
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Caixa { get; set; }
        public Nullable<int> FormaDePagamento { get; set; }
        public Nullable<decimal> MaodeObra { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<int> ClienteId { get; set; }
    
        public virtual Caixa Caixa1 { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual FormaDePagamento FormaDePagamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensVenda> ItensVenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orcamento> Orcamento { get; set; }
    }
}
